### ISSUE TITLE
Add support for nSlicers in all axis

### ISSUE THREAD

**Issue by alexfreyre** [TomekSc/MeshSlicer#1]
Amazing this addon, I really need this for a project just now! :smile: 

I need to slice some meshes but the amount of slices depends of the size of each mesh.

I can explain better with this simple example, would be amazing to slice a mesh 5 times, 10 times or 50 times per axis.
Like slice a subdivided cube by all its edges and get at the end small boxes as separated objects.

I have tried with cell fracture but the result is random and the result needed needs to be regular for any type of mesh.

There is only supported from 1 to 3 slicers would be great to add some kind of array to slicers and get nSlicer per axis.

Amazing work!
congrats!

**Comment by TomekSc** [comment]
@alexfreyre the plane creation tool ( 1-3 limit)  its just for convenience, you can slice with planes created by yourself without using this auto generation. You can set a plane with array modifier, and use the result of this as slicers, it should work.
